### ISSUE TITLE
The Project is Useful but a Mess

### ISSUE THREAD

**Issue by JerBouma** [ayhandis/creditpy#2]
Some suggestions:

- You are missing clear dependency management. Consider using something like Poetry to define the dependency and the version. Providing merely pandas in your setup.py is not enough. It will 100% break if I use Pandas v1.0.0 or v2.2.
- Consider restructuring your entire repository, seperate modules into a clear folder structure, it honestly is a bit of a mess to work with.
- Consider writing tests and utilising `pytest`, every function should have a test.
- Consider setting up proper notebooks in an examples folder, how do you utilize this release?
- Have a look at `pyproject.toml`, `setup.py` is a very old-school way of doing things.

Have a look at for example this repository and the structure that is in place: https://github.com/JerBouma/FinanceToolkit or for example: https://github.com/OpenBB-finance/OpenBBTerminal

**Comment by ayhandis** [comment]
Dear Jeroen, 

1. Thank you for your suggestions, as the package is not using complex pandas functions or the potential ones to be updated, it is not gonna break, however using a fixed version of pandas might impact the users project to crash, however I will thank about it. 
2. It is a good idea to combine all of those into one py file however I would like to provide different files for each py
3. I am planning about writing a unit test functionality. 
4. There is already an application of the package in the Read.md file. 
5.  I will be checking for the pyproject.toml recommendation. 

Thank you for your contributions. 

Kind regards,
Ayhan Dis

**Comment by JerBouma** [comment]
You are using Pandas' append which has been depreciated since [January 2022](https://pandas.pydata.org/pandas-docs/version/1.4/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append) in v1.4.0. So anyone who uses a version above v1.4.0 will run into errors and it won't work.

You don't have to combine the files in one, it just needs a proper folder structure, check the projects I've send how they do it.

**Comment by ayhandis** [comment]
- Package structure has been changed
- Development has been moved to Poetry with pyproject file. 
- Folder Structure has been changed
- Data loader has been added. 

Thanks Jeroen

Kind regards,
Ayhan Dis

**Comment by JerBouma** [comment]
Well done!
