### ISSUE TITLE
Unable to install version 2.7

### ISSUE THREAD

**Issue by hayleycooper** [ayhandis/creditpy#3]
Hi,

I’m trying to install the latest version of creditpy, but I get an error when it tries to install gap-stat 2.0.3 (regarding its build dependencies).

It looks like gap-stat 2.0.3 requires an older version of Python, but creditpy requires a newer version of Python, so I was just wondering if there was a way around this?

Thanks

**Comment by ayhandis** [comment]
Hi 

gap-stat 2.0.3 should work with Python 3.9 version, can you please try 3.9 version. 

Thanks

**Comment by hayleycooper** [comment]
Thanks for replying Ayhan, I am using Python 3.9.12 when I get the error

**Comment by ayhandis** [comment]
Can you please share the relevant error message with me? Also in the meantime please try to install another version of gap-stat, please note that I use 3.9 version.

**Comment by hayleycooper** [comment]
Hi, thank you, I've managed to install it now!
